//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdidatcuongEntities : DbContext
    {
        public AdidatcuongEntities()
            : base("name=AdidatcuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accountant> Accountants { get; set; }
        public DbSet<Agent> Agents { get; set; }
        public DbSet<DeliveryBill> DeliveryBills { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<WarehouseReceipt> WarehouseReceipts { get; set; }
        public DbSet<AccountantInfo> AccountantInfoes { get; set; }
        public DbSet<DB_Detail> DB_Detail { get; set; }
        public DbSet<Order_Detail> Order_Detail { get; set; }
        public DbSet<WR_Detail> WR_Detail { get; set; }
    }
}
