//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string AgentEmail { get; set; }
        public string AgentName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
