//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryBill
    {
        public DeliveryBill()
        {
            this.DB_Detail = new HashSet<DB_Detail>();
        }
    
        public int ID { get; set; }
        public string DBID { get; set; }
        public string OrderID { get; set; }
        public System.DateTime ExportDay { get; set; }
        public string AccountantID { get; set; }
    
        public virtual ICollection<DB_Detail> DB_Detail { get; set; }
        public virtual Order Order { get; set; }
    }
}
