//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.DeliveryBills = new HashSet<DeliveryBill>();
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int ID { get; set; }
        public string OrderID { get; set; }
        public string AgentEmail { get; set; }
        public System.DateTime OrderDay { get; set; }
        public string Status { get; set; }
        public decimal TotalMoney { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<DeliveryBill> DeliveryBills { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
