//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DB_Detail = new HashSet<DB_Detail>();
            this.Order_Detail = new HashSet<Order_Detail>();
            this.WR_Detail = new HashSet<WR_Detail>();
        }
    
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual ICollection<DB_Detail> DB_Detail { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual ICollection<WR_Detail> WR_Detail { get; set; }
    }
}
