//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_Adidatcuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseReceipt
    {
        public WarehouseReceipt()
        {
            this.WR_Detail = new HashSet<WR_Detail>();
        }
    
        public int ID { get; set; }
        public string WRID { get; set; }
        public System.DateTime ImportDay { get; set; }
        public decimal TotalMoney { get; set; }
        public string AccountantID { get; set; }
    
        public virtual ICollection<WR_Detail> WR_Detail { get; set; }
    }
}
